### ISSUE TITLE
MIGRATING FROM CENTOS "RAID ISSUE"

### ISSUE THREAD

**Issue by joazz1** [EuroLinux/eurolinux-migration-scripts#40]
Hi

The migration script started, but stopped straight with a raid compatibility issue.

See attached.

Any solution? 

Thanks
![Uploading Capture d’écran 2022-06-14 205148.png…]()

**Comment by AlexBaranowski** [comment]
Hi,

Could You provide more information about the system?

Which version of CentOS? 

- CentOS 8?
- CentOS Stream 8?
- CentOS Stream 9?

Could you try to reupload the image as it seems to be broken?

Best,
Alex

**Comment by joazz1** [comment]
Hi

Sorry it’s centos5 actually . Unfortunately .

Thanks

[My LHD Car France - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1liflu)	[1liflu]

On June 15, 2022 at 13:19 GMT, Aleksander Baranowski ***@***.***> wrote:

Hi,

Could You provide more information about the system?

Which version of CentOS?

- CentOS 8?
- CentOS Stream 8?
- CentOS Stream 9?

Could you try to reupload the image as it seems to be broken?

Best,
Alex

**Comment by aronowski** [comment]
Considering a configuration with this old CentOS version it means an individual approach - a report on the software that is installed, its configuration and replicating it on new machines with a modern EuroLinux version.
I will be happy to assist you with such process but it's paid. For the price and other aspects please contact us with the contact form at https://en.euro-linux.com/company/contact/.

**Comment by AlexBaranowski** [comment]
@joazz1 I'm closing the issue as CentOS 5 is not supported for the last 5 years  (CentOS hit EOL 2017-03-31).

Still, if Your company needs support with migrating from older systems to supported ones (EuroLinux, Oracle Linux or Red Hat), You can contact our sales. This kind of work is part of our organisation's TU (Technical Unit) support, and **is not part of the standard support**.

Best,
Alex
